"""create alerts table

Revision ID: 75b1857f2b7c
Revises: f79f1728028c
Create Date: 2026-09-18 12:16:10.926679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b1857f2b7c'
down_revision: Union[str, Sequence[str], None] = 'f79f1728028c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('device_offline', 'high_cpu', 'high_memory', 'high_latency', name='alert_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'critical', name='alert_severity_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_device_resolved_created', 'alerts', ['device_id', 'resolved', 'created_at'], unique=False)
    op.create_index('uq_alerts_unresolved_device_type', 'alerts', ['device_id', 'alert_type'], unique=True, postgresql_where=sa.text('resolved = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_alerts_unresolved_device_type', table_name='alerts', postgresql_where=sa.text('resolved = false'))
    op.drop_index('ix_alerts_device_resolved_created', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
