"""create devices table

Revision ID: a5c00acc34fd
Revises: 
Create Date: 2026-09-17 04:36:44.823044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5c00acc34fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_type', sa.Enum('router', 'server', 'switch', name='device_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'online', 'offline', name='device_status_enum'), server_default='unknown', nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('ip_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("devices")

    postgresql.ENUM(name="device_status_enum").drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(name="device_type_enum").drop(
        op.get_bind(),
        checkfirst=True,
    )