"""create metrics table

Revision ID: f79f1728028c
Revises: a5c00acc34fd
Create Date: 2026-09-17 22:46:53.950130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79f1728028c'
down_revision: Union[str, Sequence[str], None] = 'a5c00acc34fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cpu_usage BETWEEN 0 AND 100', name='ck_metrics_cpu_usage_range'),
    sa.CheckConstraint('latency_ms >= 0', name='ck_metrics_latency_nonnegative'),
    sa.CheckConstraint('memory_usage BETWEEN 0 AND 100', name='ck_metrics_memory_usage_range'),
    sa.CheckConstraint('uptime_seconds >= 0', name='ck_metrics_uptime_nonnegative'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_device_recorded_at', 'metrics', ['device_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_device_recorded_at', table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
